//// <auto-generated />
//using System;
//using CallCenterAgentManager.Data.Context;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Data.Migrations
//{
//    [DbContext(typeof(CallCenterAgentManager.Data.Context.CallCenterAgentManager))]
//    [Migration("20230724105140_InitialMigration")]
//    partial class InitialMigration
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.9")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("CallCenterAgentManager.Domain.Entities.Comment", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Author")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Content")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreationDate")
//                        .HasColumnType("datetime2");

//                    b.Property<Guid>("PostId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.ToTable("Comments");
//                });

//            modelBuilder.Entity("CallCenterAgentManager.Domain.Entities.Post", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Content")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreationDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Posts");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
